### PR TITLE
Updated pandoc filter to properly handle line continuation with prompts

### PR DESCRIPTION
**Pull request by moorepants**
The current filter fails to discover Python line continuation prompts
that do not have any characters after the '...'. This patch detects for
that and includes some other formatting improvements.

### CODE REVIEW

**Comment by nthiery** [comment]
Dear Jason,

Thanks much for the improvements! I went through the changes, and they look good. Since the changes in the logic were mixed with the changes in the formatting, I can't swear I did not miss an issue in the logic. Next time, two separate commits would help the review.

Beside running the tests, did you get a chance to double check by hand the new outputs?

If yes, then I'll just merge as is.

Thanks again,

**Comment by nthiery** [comment]
(yeah, we are missing good continuous integration here ...)

**Comment by moorepants** [comment]
Sorry about the mixed commits. I started editing the file just thinking I'd have a fork on my own machine, so didn't organize it well.

Let me run makefile locally and make sure it didn't screw up any other outputs in the other documents, as I didn't check those.

**Comment by moorepants** [comment]
I found one more issue associated with `...` that shows up in outputs and fixed it. I ran make locally and checked the output of all.ipynb and it looks good.

**Comment by nthiery** [comment]
>    I found one more issue associated with ... that shows up in outputs and
>    fixed it. I ran make locally and checked the output of all.ipynb and it
>    looks good.

Excellent. I'll try to have a look later today. Thanks!

**Comment by nthiery** [comment]
Oops, for some value of today ... Sorry went under the radar. Thanks a lot for the contribution!

**Comment by nthiery** [comment]
I'll now make a new release including this.

**Pull request merged**
